"use client";

import { useEffect, useState, Suspense } from "react";
import { LandingPagePreview } from "@/components/LandingPagePreview";
import { LandingPageBlueprint } from "@/lib/ai-generator";
import { Button } from "@/components/ui/Button";
import { ArrowLeft, ExternalLink, Download, Layout, Sparkles } from "lucide-react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";

function FullPreviewContent() {
  const router = useRouter();
  const [blueprint, setBlueprint] = useState<LandingPageBlueprint | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const savedBlueprint = localStorage.getItem("current_blueprint");
    if (savedBlueprint) {
      try {
        setBlueprint(JSON.parse(savedBlueprint));
      } catch (e) {
        console.error("Error parsing saved blueprint:", e);
      }
    }
    setIsLoading(false);
  }, []);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-black flex items-center justify-center text-white">
        <div className="flex flex-col items-center gap-4">
          <div className="w-12 h-12 border-4 border-blue-500/20 border-t-blue-500 rounded-full animate-spin" />
          <p className="text-gray-500 font-bold uppercase tracking-widest text-xs">Loading Preview...</p>
        </div>
      </div>
    );
  }

  if (!blueprint) {
    return (
      <div className="min-h-screen bg-black flex flex-col items-center justify-center text-white p-6 text-center">
        <h1 className="text-3xl font-bold mb-4 text-red-400">Preview Not Found</h1>
        <p className="text-gray-400 max-w-md mb-8">
          It looks like the generated preview data has expired or was not saved correctly.
        </p>
        <Button variant="glow" onClick={() => router.push("/dashboard")}>
          <ArrowLeft className="w-4 h-4 mr-2" /> Back to Dashboard
        </Button>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-black text-white selection:bg-blue-500/30">
      {/* Control Bar */}
      <div className="fixed top-6 left-1/2 -translate-x-1/2 z-50 flex items-center gap-4 bg-black/50 backdrop-blur-xl border border-white/10 px-6 py-3 rounded-full shadow-2xl">
        <Button variant="outline" size="sm" onClick={() => router.push("/dashboard")} className="h-10">
          <ArrowLeft className="w-4 h-4" /> Back to Editor
        </Button>
        <div className="w-px h-6 bg-white/10" />
        <div className="text-sm font-medium flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-blue-400" />
          <span>Previewing: <span className="text-blue-400">{blueprint.businessName}</span></span>
        </div>
        <div className="w-px h-6 bg-white/10" />
        <Button variant="glow" size="sm" className="h-10">
          <Download className="w-4 h-4" /> Export Code
        </Button>
      </div>

      <main className="pt-24">
        <LandingPagePreview blueprint={blueprint} />
      </main>

      <footer className="py-12 border-t border-white/5 text-center bg-black/40">
        <p className="text-gray-500 text-sm">Generated by LaunchForge AI • 2026</p>
      </footer>
    </div>
  );
}

export default function FullPreview() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-black flex items-center justify-center text-white">
        <div className="flex flex-col items-center gap-4">
          <div className="w-12 h-12 border-4 border-blue-500/20 border-t-blue-500 rounded-full animate-spin" />
          <p className="text-gray-500 font-bold uppercase tracking-widest text-xs">Loading Full Preview...</p>
        </div>
      </div>
    }>
      <FullPreviewContent />
    </Suspense>
  );
}
